"""updated job record test

Revision ID: 1a9f92f46693
Revises: 8c2f3421c6b6
Create Date: 2026-09-10 11:27:16.114345

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1a9f92f46693'
down_revision: Union[str, Sequence[str], None] = '8c2f3421c6b6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('job_records',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('job_type', sa.String(length=50), nullable=False),
    sa.Column('target_id', sa.String(length=100), nullable=False),
    sa.Column('idempotency_key', sa.String(length=100), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('attempts', sa.Integer(), nullable=False),
    sa.Column('max_attempts', sa.Integer(), nullable=False),
    sa.Column('last_error', sa.String(length=2000), nullable=True),
    sa.Column('last_error_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('next_retry_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('payload', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('idempotency_key')
    )
    op.create_index(op.f('ix_job_records_job_type'), 'job_records', ['job_type'], unique=False)
    op.create_index(op.f('ix_job_records_status'), 'job_records', ['status'], unique=False)
    op.create_index(op.f('ix_job_records_target_id'), 'job_records', ['target_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_job_records_target_id'), table_name='job_records')
    op.drop_index(op.f('ix_job_records_status'), table_name='job_records')
    op.drop_index(op.f('ix_job_records_job_type'), table_name='job_records')
    op.drop_table('job_records')
    # ### end Alembic commands ###
