"""added datetime

Revision ID: 25e5b9d25d39
Revises: 38f6ce3d9bdb
Create Date: 2026-09-01 14:32:14.738179

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '25e5b9d25d39'
down_revision: Union[str, Sequence[str], None] = '38f6ce3d9bdb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('screenings', sa.Column('enrolled_at', sa.DateTime(timezone=True), nullable=True))
    op.drop_column('screenings', 'labels')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('screenings', sa.Column('labels', sa.VARCHAR(length=500), nullable=True))
    op.drop_column('screenings', 'enrolled_at')
    # ### end Alembic commands ###
