"""added labels instaed of the notes

Revision ID: 38f6ce3d9bdb
Revises: 9667e31b344a
Create Date: 2026-09-01 12:55:35.940905

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '38f6ce3d9bdb'
down_revision: Union[str, Sequence[str], None] = '9667e31b344a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('screenings', sa.Column('labels', sa.String(length=500), nullable=True))
    op.drop_column('screenings', 'notes')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('screenings', sa.Column('notes', sa.VARCHAR(length=500), nullable=True))
    op.drop_column('screenings', 'labels')
    # ### end Alembic commands ###
