"""create screenings and sites tables

Revision ID: 5597213644ee
Revises: 
Create Date: 2026-08-31 18:14:33.248069

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5597213644ee'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('screenings',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('site_id', sa.String(length=50), nullable=False),
    sa.Column('candidate_initials', sa.String(length=4), nullable=False),
    sa.Column('age', sa.Integer(), nullable=False),
    sa.Column('sex', sa.String(length=1), nullable=False),
    sa.Column('diagnosis', sa.String(length=200), nullable=False),
    sa.Column('medications', sa.JSON(), nullable=False),
    sa.Column('is_pregnant', sa.Boolean(), nullable=False),
    sa.Column('has_liver_disease', sa.Boolean(), nullable=False),
    sa.Column('in_other_trial', sa.Boolean(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('eligibility_result', sa.String(length=20), nullable=True),
    sa.Column('failed_criteria', sa.JSON(), nullable=True),
    sa.Column('subject_id', sa.String(length=20), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('subject_id')
    )
    op.create_index(op.f('ix_screenings_site_id'), 'screenings', ['site_id'], unique=False)
    op.create_index('ix_screenings_site_status', 'screenings', ['site_id', 'status'], unique=False)
    op.create_index(op.f('ix_screenings_status'), 'screenings', ['status'], unique=False)
    op.create_table('sites',
    sa.Column('id', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('sites')
    op.drop_index(op.f('ix_screenings_status'), table_name='screenings')
    op.drop_index('ix_screenings_site_status', table_name='screenings')
    op.drop_index(op.f('ix_screenings_site_id'), table_name='screenings')
    op.drop_table('screenings')
    # ### end Alembic commands ###
