"""added new column notes

Revision ID: 9667e31b344a
Revises: 5597213644ee
Create Date: 2026-09-01 12:31:16.478434

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9667e31b344a'
down_revision: Union[str, Sequence[str], None] = '5597213644ee'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('screenings', sa.Column('notes', sa.String(length=500), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('screenings', 'notes')
    # ### end Alembic commands ###
